"""empty message

Revision ID: f1b2152f2cb6
Revises: 
Create Date: 2022-07-30 17:42:37.957401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b2152f2cb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('date_added', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_age'), 'users', ['age'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_age'), table_name='users')
    op.drop_column('users', 'age')
    op.drop_column('posts', 'date_added')
    # ### end Alembic commands ###
